# Generated by Django 5.0.1 on 2024-02-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('invoice_date', models.DateField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('order_number', models.CharField(max_length=20)),
                ('ct_number', models.CharField(max_length=20)),
                ('job_number', models.CharField(max_length=20)),
                ('kt_number', models.CharField(max_length=20)),
                ('date_in', models.DateField()),
                ('invoice_number', models.CharField(max_length=20)),
                ('date_due', models.DateField()),
                ('metal_type', models.CharField(max_length=100)),
                ('setter', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('shipping_details', models.CharField(max_length=255)),
                ('setting_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('polish_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rhodium_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soldering_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscellaneous_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_stone_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finding_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diamonds_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mounting_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diamond_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('polish', models.BooleanField(default=False)),
                ('rush', models.BooleanField(default=False)),
                ('rhodium', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('order', models.BooleanField(db_column='order_made', default=False)),
                ('stamp', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=False)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/orders/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='StoneSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=100)),
                ('cut', models.CharField(max_length=100)),
                ('stone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carat_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='orders.order')),
            ],
        ),
    ]
