# Generated by Django 4.2.10 on 2024-02-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ct_number', models.CharField(blank=True, max_length=20, null=True)),
                ('job_number', models.CharField(blank=True, max_length=20, null=True)),
                ('kt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_details', models.CharField(blank=True, max_length=255, null=True)),
                ('metal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('setter', models.CharField(blank=True, max_length=255, null=True)),
                ('date_in', models.DateField(auto_now_add=True, null=True)),
                ('date_due', models.DateField()),
                ('setting_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('polish_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rhodium_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soldering_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color_stone_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finding_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diamonds_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mounting_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_polish', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rush', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rhodium', models.BooleanField(blank=True, default=False, null=True)),
                ('is_repair', models.BooleanField(blank=True, default=False, null=True)),
                ('is_order', models.BooleanField(blank=True, default=False, null=True)),
                ('is_stamp', models.BooleanField(blank=True, default=False, null=True)),
                ('is_clean', models.BooleanField(blank=True, default=False, null=True)),
                ('polish_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('rush_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('rhodium_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('repair_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('order_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('stamp_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('clean_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='StoneSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=100)),
                ('cut', models.CharField(max_length=100)),
                ('stone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('carat_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/orders/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
        ),
    ]
