# Generated by Django 5.0.1 on 2024-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clean',
            new_name='is_clean',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='polish',
            new_name='is_order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='repair',
            new_name='is_polish',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rhodium',
            new_name='is_repair',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rush',
            new_name='is_rhodium',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stamp',
            new_name='is_rush',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='clean_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_stamp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='polish_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='repair_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rhodium_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rush_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stamp_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
