# Generated by Django 4.2.13 on 2024-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_setting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='setting_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
