# Generated by Django 4.2.10 on 2024-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
