# Generated by Django 4.2.13 on 2024-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_is_setting_order_is_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resize',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
