# Generated by Django 4.2.13 on 2024-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_resize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonespecification',
            name='carat_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stonespecification',
            name='cut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stonespecification',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stonespecification',
            name='stone_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
