# Generated by Django 4.2.13 on 2024-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_stonespecification_carat_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonespecification',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
