# Generated by Django 4.2.10 on 2024-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='abbreviation',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
