# Generated by Django 4.2.13 on 2024-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addresss',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
