# Generated by Django 4.2.13 on 2024-06-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_addresss_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addresss',
            new_name='address',
        ),
    ]
