# Generated by Django 4.2.13 on 2024-05-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_shipping_address_invoiceitem_lot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='lot_number',
        ),
    ]
