# Generated by Django 4.2.13 on 2024-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
