# Generated by Django 4.2.13 on 2024-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoiceitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='the_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
