# Generated by Django 4.2.13 on 2024-05-23 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoiceitem_the_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_in']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
